import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Header from '../components/common/header';
import Footer from '../components/common/footer';

export default function Contact() {
  return (
    <div className={styles.container}>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Contact Us
        </h1>
      </main>

     
      <Footer />
    </div>
  )
}
