import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import feature from '../styles/Feature.module.css';
import Header from '../components/common/header';
import Footer from '../components/common/footer';
import Table from '../components/common/table';

const isServer = () => typeof window === 'undefined';
async function getPersonaData () {
  const res = await fetch(`https://business.paytm.com/api/v1/content/json?slug=blogs&live`);
  const data = await res.json();
  if (!data) {
    return {
      notFound: true,
    }
  }
  return {
    props: { data }, 
  }
  };

function Features(props) {
  return (
    <div className={styles.container}>
      <Header />
     {/* { console.log(props?.props?.data)} */}
      <Head>
        <title>dudu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Our Feature Products
        </h1>
       <div className={feature.blog}>
            <Table props={props?.data} />
       </div>
        
      </main>

    
      <Footer />
    </div>
  )
}

export const getServerSideProps = async (context) => {
  if(isServer()) { debugger
    const personaData= await getPersonaData()
    return personaData;
  }
  else {
    return  null;
  }
}
export default Features;