import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Header from '../components/common/header';
import Footer from '../components/common/footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.banner}>
          <h1 className={styles.title}>
            Welcome to OCSWEB 
          </h1>
          <p className={styles.description}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
          </p>
          <h4 className={styles.subtitle}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, </h4>
        </div>
       <div className={styles.bannercta}>
         <button className={styles.bannerBtn}>
            <span>Our Services</span>
         </button>
         <button className={styles.bannerBtn}>
            <span>Our Workshop</span>
         </button>
       </div>
      </main>

     {/* <Footer /> */}
    </div>
  )
}
